### ISSUE TITLE
[Implementation] Event-Requesting Form

### ISSUE THREAD

**Issue by cameronsuen** [tangoclinh1995/thehonorclub-mobileapp#2]
We should have a basic form for requesting an event so that a proper event can be set up in which people could form teams.  It could include the following details:

- Event Name
- Event Date/Time
- Min/Max Group Size (optional)

**Comment by linhnta925** [comment]
Hi @hpsuenaa, perhaps I understand why your code always run slow on your computer.
Maybe the problem is here:

```
var ref = firebase.database().ref().child("event");
$scope.events = $firebaseArray(ref);
```

When you do this, the **WHOLE** event array will be constantly monitored and synchronized with Firebase database, which can be resource-consuming (that's why your browser run very slows).

Meanwhile, you only want to insert a new event into database and it is not necessary to download and monitor the whole array. Therefore, you should consider using more efficient method, such as:

```
firebase.database().ref().push(<NEW_EVENT_OBJECT>)
```

**Comment by cameronsuen** [comment]
Thanks, will try that out to improve performance!
