### ISSUE TITLE
[Question] Unit Testing UI components

### ISSUE THREAD

**Issue by cameronsuen** [tangoclinh1995/thehonorclub-mobileapp#25]
I am having issues with testing the controller.  Since the majority of the code is UI-related code (e.g. calling date/timepicker), it is very hard to unit test those and the coverage rate is very low(~50%), any ideas on how to unit test these, or should I leave them be at all?

![image](https://cloud.githubusercontent.com/assets/9823116/20244570/c416ec02-a9c2-11e6-8758-2d9184077495.png)

![image](https://cloud.githubusercontent.com/assets/9823116/20244580/13a9e882-a9c3-11e6-95ea-9b3023cd15f8.png)

**Comment by linhnta925** [comment]
In this situation, you canot directly interact with the UI, but basically what you want to achieve is to manipulate the **ionicTimePicker** and **ionicDatePicker** services. In particular, in you unit test, you want to be able to:
- Call functions: **ionicTimePicker.openTimePicker()**
- Call the **callback** function of the **startTimeObj** and **endTimeObj**
- Call functions: **ionicDatePicker.openDatePicker()**
- Call the **callback** function of the **startDateObj** and **endDateObj**

To acheive these, you need to, inject a "fake" **ionicTimePicker** and **ionicDatePicker** into your controller (basically insert fake objects instead of the real services), add a spy on functions **openDatePicker** and **openTimePicker** of those faked objects.

You can take a look that methods *_spyOn, .and.callFake, .and.returnValue, ..._ in Jasmine documentation:
https://jasmine.github.io/2.5/introduction.html#section-Spies

**Comment by sleeplessclassics** [comment]
I can help you out with the unit testing for Events.
