### ISSUE TITLE
[Discussion] Facebook OAuth requires server

### ISSUE THREAD

**Issue by jshin49** [tangoclinh1995/thehonorclub-mobileapp#9]
Facebook OAuth will require a server and a URL, otherwise it won't send out the request.

How will this work on mobile?

Will this be solved if we connect OAuth through Firebase?

Our Ionic App wouldn't be hosted on Firebase, instead IonicView seems better choice.

Just FYI, we can use Firebase for Hosting our entire project (it can also be a server).

The web version, we probably will host it on Firebase, but as you may know, Ionic version is an App, with all the files stored in the phone.

Facebook OAuth doesn't like this, when there is no server serving these HTML files.

**Comment by linhnta925** [comment]
Have you met the similar situation mentioned in this link:
http://stackoverflow.com/questions/25225280/facebook-app-firebase-simple-login-url-error

Perhaps you can try the solution mentioned here.

**Comment by jshin49** [comment]
That is precisely our problem

We cannot host an IONIC app on localhost server on the phone.

But lets investigate how it works on Ionic blog post.

Perhaps they have a solution.
1. 11. 9. 15:52에 "Ngoc Linh Ta" notifications@github.com님이 작성:

**Comment by tangoclinh1995** [comment]
Check this link: https://github.com/angular/angularfire2/issues/243

User jlsuarezs in the discussion said that Firebase can solve the problem. I guess it does so by using **firebase.auth().signInWithPopup(provider)** instead of **firebase.auth().signInWithRedirect(provider)**

**signinWithPopup seems to not require a redirect URL**. I think it's reasonable, because native app (programmed in Objective-C, Java) can't have redirect URL as well, as they can still work with OAuth.

You can check the details here as well: 
https://firebase.google.com/docs/auth/web/facebook-login

I haven't tried it so I don't know whether it can solve the problem

**Comment by linhnta925** [comment]
Perhaps you can try this solution ngCordovaOAuth:
- Installation: https://github.com/nraboy/ng-cordova-oauth (note that Cordova Whitelist Plugin has already been installed in the project)
- Example (with Facebook): https://github.com/nraboy/ng-cordova-facebook-example/blob/master/www/js/app.js
- Integrate ngCordovaOAuth with Firebase: https://gist.github.com/katowulf/de9ef6b04552091864fb807092764224
